// pages/generador-de-numeros.vue
<script setup lang="ts">
useSeoMeta({
  title: "Generador de números",
});

const numbers = ref(randomInteger(1, 1000).toString());
const data = ref<number[]>([]);

function generateRandomNumber() {
  numbers.value = randomInteger(1, 1000).toString();
  generateData();
}

function generateData() {
  const n = Number.parseInt(numbers.value);
  if (Number.isNaN(n)) return;

  let array: number[] = [];
  for (let i = 0; i < n; i++) {
    array[i] = Math.random();
  }
  data.value = array;
}

onMounted(() => generateData());
</script>

<template>
  <div class="mx-auto my-0 max-w-xl">
    <div class="flex w-full justify-center gap-2 text-center">
      <input type="number" v-model="numbers" />
      <button type="button" secondary @click="generateRandomNumber">
        Aleatorio
      </button>
      <button type="button" @click="generateData">Generar</button>
    </div>
    <div class="mt-4">
      <p v-for="number in data">{{ number }}</p>
    </div>
  </div>
</template>

// src/app/generador-de-numeros/page.tsx
"use client";

import { useState } from "react";
import { randomNumber } from "~/helpers/random-number";

export default function Page() {
  const [numbers, setNumbers] = useState(randomNumber(1, 1000).toString());
  const [numbersList, setNumbersList] = useState<number[]>([]);

  function automaticMode() {
    setNumbers(randomNumber(1, 1000).toString());
    generate();
  }

  function generate() {
    const n = Number.parseInt(numbers);
    if (Number.isNaN(n)) return;

    let a: number[] = [];
    for (let i = 0; i < n; i++) {
      a[i] = Math.random();
    }
    setNumbersList(a);
  }

  return (
    <div className="mx-auto my-0 max-w-xl">
      <div className="w-full justify-center text-center flex gap-2">
        <input
          type="number"
          value={numbers}
          onChange={(e) => setNumbers(e.target.value)}
          className="border bg-black/10 rounded-lg px-4 py-2 w-36"
        />
        <button
          className="bg-black/10 border rounded-lg px-4 py-2"
          onClick={automaticMode}
        >
          Aleatorio
        </button>
        <button
          className="bg-purple-500 text-white border rounded-lg px-4 py-2"
          onClick={generate}
        >
          Generar
        </button>
      </div>
      <div className="mt-4">
        {numbersList.map((item, index) => (
          <p key={index}>{item}</p>
        ))}
      </div>
    </div>
  );
}
