// src/app/paracaidista/page.tsx
"use client";

import "chart.js/auto";
import ChartDataLabels from "chartjs-plugin-datalabels";
import { useEffect, useState } from "react";
import { Line } from "react-chartjs-2";
import { round } from "~/helpers/decimals";

// gravedad
const g = 9.8;
// resistencia
const c = 12.5;

type Fila = { t: number; v: number };

function f(m: number, t: number) {
  return ((g * m) / c) * (1 - Math.pow(Math.E, -(c / m) * t));
}

export default function Paracaidista() {
  const [decimals, setDecimals] = useState(15);
  const [mass, setMass] = useState(68.1);
  const [interval, setInterval] = useState(2);
  const [data, setData] = useState<Fila[]>();

  useEffect(() => {
    if (Number.isNaN(mass) || Number.isNaN(interval)) return;

    let t = 0,
      v = round(f(mass, t), decimals);

    let arr: Fila[] = [{ t, v }];

    while (true) {
      t += interval;
      v = round(f(mass, t), decimals);
      if (v == arr[arr.length - 1].v) break;
      arr.push({ v, t });
    }

    setData(arr);
  }, [mass, interval, decimals]);

  return (
    <>
      <div className="flex flex-col-reverse md:flex-row max-w-6xl mx-auto my-0 justify-start">
        <div className="w-full md:w-48 flex flex-col gap-2">
          <div>
            <span>Intervalo: </span>
            <input
              type="number"
              className="border bg-black/10 p-1 w-12 text-center"
              onChange={(e) => setInterval(Number.parseInt(e.target.value))}
              value={interval}
            />
          </div>
          <div>
            <span>Peso: </span>
            <input
              type="number"
              className="border bg-black/10 p-1 w-16 text-center"
              onChange={(e) => setMass(Number.parseFloat(e.target.value))}
              value={mass}
            />
          </div>
          <div>
            <span>Decimales: </span>
            <input
              type="number"
              className="border bg-black/10 p-1 w-16 text-center"
              onChange={(e) => setDecimals(Number.parseInt(e.target.value))}
              value={decimals}
            />
          </div>
          {data && (
            <table className="w-full border">
              <thead>
                <tr className="bg-black/20">
                  <th>t</th>
                  <th>v</th>
                </tr>
              </thead>
              <tbody>
                {data.map((v) => (
                  <tr key={v.t} className="text-center even:bg-black/10">
                    <td>{v.t}</td>
                    <td>{v.v}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
        <div className="flex flex-grow w-full relative">
          {data && (
            <Line
              plugins={[ChartDataLabels]}
              options={{
                plugins: {
                  datalabels: {
                    align: "top",
                  },
                },
                responsive: true,
                scales: {
                  y: {
                    ticks: {
                      stepSize: 5,
                    },
                  },
                },
              }}
              data={{
                labels: data.map((v) => v.t),
                datasets: [
                  {
                    label: "Velocidad",
                    data: data.map((v) => v.v),
                    fill: true,
                    borderColor: "purple",
                    tension: 0.1,
                  },
                ],
              }}
            />
          )}
        </div>
      </div>
    </>
  );
}

// pages/paracaidista.vue
<script setup lang="ts">
import {
  CategoryScale,
  Chart,
  LinearScale,
  type ChartData,
  Title,
  Tooltip,
  PointElement,
  LineElement,
  Legend,
  Filler,
} from "chart.js";
import { Line } from "vue-chartjs";
import ChartDataLabels from "chartjs-plugin-datalabels";

useSeoMeta({
  title: "Paracaidista",
});

const m = 68.1;
const g = 9.8;
const c = 12.5;

const decimals = ref("16");
const interval = ref("2");
const data = ref<number[][]>([]);

const f = (t: number) => ((g * m) / c) * (1 - Math.pow(Math.E, -(c / m) * t));

function generateData() {
  const numberDecimals = Number.parseInt(decimals.value);
  const numberInterval = Number.parseInt(interval.value);
  if (Number.isNaN(numberDecimals) || Number.isNaN(numberInterval)) return;

  let t = 0;
  let v = roundDecimals(f(t), numberDecimals);

  let table: number[][] = [[t, v]];
  while (true) {
    t += numberInterval;
    v = roundDecimals(f(t), numberDecimals);
    if (v == table[table.length - 1][1]) break;
    table.push([t, v]);
  }

  data.value = table;
}

Chart.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  ChartDataLabels,
  Filler,
);

const chartData = computed(
  (): ChartData<"line", number[], number> => ({
    labels: data.value.map((v) => v[0]),
    datasets: [
      {
        label: "Velocidad",
        data: data.value.map((v) => v[1]),
        fill: true,
        borderColor: "purple",
      },
    ],
  }),
);

onMounted(() => generateData());

watch([decimals, interval], generateData);
</script>

<template>
  <div
    class="mx-auto my-0 flex max-w-6xl flex-col-reverse justify-start md:flex-row">
    <div class="flex w-full flex-col gap-2 md:w-52">
      <div>
        <span>Intervalo: </span>
        <input type="number" v-model="interval" class="w-16" />
      </div>
      <div>
        <span>Decimales: </span>
        <input type="number" v-model="decimals" class="w-16" />
      </div>
      <table>
        <thead>
          <tr class="bg-black/10 text-center font-bold">
            <td>t</td>
            <td>v</td>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in data" class="odd:bg-black/5">
            <td class="bg-black/5 text-center">{{ row[0] }}</td>
            <td>{{ row[1] }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="relative flex w-full flex-row">
      <Line
        :data="chartData"
        :plugins="[ChartDataLabels]"
        :options="{
          responsive: true,
          scales: {
            y: {
              ticks: {
                stepSize: 5,
              },
            },
          },
          plugins: {
            datalabels: {
              align: 'top',
            },
          },
        }" />
    </div>
  </div>
</template>
